mugla/mugla/Controllers/uyesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mugla.Models;

namespace mugla.Controllers
{
    public class uyesController : Controller
    {
        private muglawebdbEntities db = new muglawebdbEntities();

        // GET: uyes
        public ActionResult Index()
        {
            return View(db.uye.ToList());
        }

        // GET: uyes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            uye uye = db.uye.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // GET: uyes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: uyes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,email,sifre,adi,soyadi")] uye uye)
        {
            if (ModelState.IsValid)
            {
                db.uye.Add(uye);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(uye);
        }

        


        // GET: uyes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            uye uye = db.uye.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(uye l)
        {
            if(ModelState.IsValid)
            {
                var details = (from uye in db.uye
                               where l.email == uye.email && l.sifre == uye.sifre
                               select new
                               {
                                   l.id,
                                   l.adi
                               }).ToList();
                if(details.FirstOrDefault() != null)
                {
                    Session["Id"] = details.FirstOrDefault().id;
                    Session["adi"] = details.FirstOrDefault().adi;
                    return RedirectToAction("Welcome", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "invalid credendetails");
            }
            return View(l);
        }


        // POST: uyes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,email,sifre,adi,soyadi")] uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uye).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uye);
        }

        // GET: uyes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            uye uye = db.uye.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // POST: uyes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            uye uye = db.uye.Find(id);
            db.uye.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

mugla/mugla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Muğla</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS
    ================================================== -->
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    
    <link href="~/Content/bootstrap-responsive.css" rel="stylesheet" />
    
    <link href="~/Content/prettyPhoto.css" rel="stylesheet" />
    
    <link href="~/Content/flexslider.css" rel="stylesheet" />
    
    <link href="~/Content/custom-styles.css" rel="stylesheet" />

    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <link rel="stylesheet" href="css/style-ie.css"/>
    <![endif]-->
    <!-- Favicons
    ================================================== -->
    <link rel="shortcut icon" href="~/img/favicon.ico">
    <link rel="apple-touch-icon" href="~/img/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/img/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/img/apple-touch-icon-114x114.png">

    <!-- JS
    ================================================== -->
    <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    
   
    <script src="~/Scripts/jquery.prettyPhoto.js"></script>
    
    <script src="~/Scripts/jquery.flexslider.js"></script>
    
    <script src="~/Scripts/jquery.custom.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $("#btn-blog-next").click(function () {
                $('#blogCarousel').carousel('next')
            });
            $("#btn-blog-prev").click(function () {
                $('#blogCarousel').carousel('prev')
            });

            $("#btn-client-next").click(function () {
                $('#clientCarousel').carousel('next')
            });
            $("#btn-client-prev").click(function () {
                $('#clientCarousel').carousel('prev')
            });

        });

        $(window).load(function () {

            $('.flexslider').flexslider({
                animation: "slide",
                slideshow: true,
                start: function (slider) {
                    $('body').removeClass('loading');
                }
            });
        });

    </script>

</head>
<body>
    <!-- Color Bars (above header)-->
    <div class="color-bar-1"></div>
    <div class="color-bar-2 color-bg"></div>

    <div class="container">

        <div class="row header">
            <!-- Begin Header -->
            <!-- Logo
            ================================================== -->
            <div class="span5 logo">
                <img src="~/Galeri/muglalogo.png" width="100" height="100" alt="" />
                <h5>Her köşesinde başka bir güzellik Mugla...</h5>
            </div>

            <!-- Main Navigation
            ================================================== -->
            <div class="span7 navigation">
                <div class="navbar hidden-phone">

                    <ul class="nav">
                        <li>@Html.ActionLink("Anasayfa", "Index", "Home")</b></a></li>


                        <li class="dropdown">
                            <a href="index.htm" class="dropdown-toggle" data-toggle="dropdown">Haberler@*<b class="caret"></b>*@</a>
                            @*<ul class="dropdown-menu">
                                <li><a href="features.htm">Hizmetler</a></li>
                                <li><a href="blog-style2.htm">Blog Style 2</a></li>

                            </ul>*@
                        </li>


                        @*<li class="dropdown">
                            <a href="index.htm" class="dropdown-toggle" data-toggle="dropdown">Kültür Sanat@*<b class="caret">*@</b></a>
                            @*<ul class="dropdown-menu">
                                <li><a href="blog-style1.htm">Blog Style 1</a></li>
                                <li><a href="blog-style2.htm">Blog Style 2</a></li>
                                <li><a href="blog-style3.htm">Kampüs Haberleri</a></li>
                                <li><a href="blog-style4.htm">Kampüsten Manzaralar</a></li>
                                <li><a href="blog-single.htm">Blog Single</a></li>
                            </ul>*@
                        </li>

                       
                        </li>


                        <li>@Html.ActionLink("Galeri", "Galeri", "Home") </a></li>


                        
                            <li>@Html.ActionLink("Üye Ol", "Create", "uyes")</li>
                            
                              
                                
                            
                        
                        <li>@Html.ActionLink("Giriş Yap", "Login", "uyes")</li>
                        <li>@Html.ActionLink("Admin", "Index", "uyes")</li>
                 </ul>

                </div>

                <!-- Mobile Nav
                ================================================== -->
                <form action="#" id="mobile-nav" class="visible-phone">
                    <div class="mobile-nav-select">
                        <select onchange="window.open(this.options[this.selectedIndex].value,'_top')">
                            <option value="">Site Haritasi</option>
                            <option value="index.htm">Anasayfa</option>
                            <option value="index.htm">Haberler</option>
                            
                            <option value="gallery-4col.htm">Galeri</option>
                            <option value="page-contact.htm">@Html.ActionLink("Giriş Yap", "Login", "uyes")Giriş Yap</option>
                            <option value="page-contact.htm">@Html.ActionLink("Üye Ol", "Create", "uyes")Üye Ol</option>
                        </select>
                    </div>
                </form>

            </div>

        </div><!-- End Header -->
    @RenderBody()
        <div class="footer-container">
            <div class="container">
                <div class="footer-row">
                    <div class="span3 footer-col">
                        <h5>Hakkimizda</h5>

                        <address>
                            <strong>Tasarim Ekibi</strong><br />
                            Mugla Sitki Koçman Üniversitesi Üniversite-Sanayi Is Birligi Koordinatörlügü,Arastirma Laboratuvari Merkezi (ALM) Kötekli Kampüsü PK: 48000 Mentese/Mugla<br />
                            <br />
                            <p>&copy;@DateTime.Now.Year CampusDesign</p>
                        </address>
                        <ul class="social-icons">
                            <h5>DIGER BAGLANTILAR</h5>
                            <li><a href="https://tr-tr.facebook.com/muglaedutr/" class="social-icon facebook"></a></li>
                            <li><a href="https://twitter.com/muglaunivercity" class="social-icon twitter"></a></li>
                        </ul>
                    </div>

                    <div class="span3 footer-col">
                    </div>



                    <div class="span3 footer-col">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3179.4861369676846!2d28.373717230393105!3d37.16491641007877!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14bf73c9263b4757%3A0x3a1020fa0911b7a4!2zTXXEn2xhIFPEsXRrxLEgS2_Dp21hbiDDnG5pdmVyc2l0ZXNp!5e0!3m2!1str!2str!4v1511967824775" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div><!-- End Footer -->
</body>
</html>